version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - ci

  - package-ecosystem: pnpm
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
  
  - package-ecosystem: pnpm
    target-branch: main
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm

  - package-ecosystem: pnpm
    target-branch: main
    directory: /apps/docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
