# fly.toml app configuration file generated for openstatus-checker on 2023-10-23T11:41:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "openstatus-checker"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "1m0s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/ping"

[checks]
  [checks.name_of_your_http_check]
    port = 3000
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/ping"
